/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Play Sound
 #	author : miyako
 #	2014/07/03
 #
 # --------------------------------------------------------------------------------*/



// --- Play Sound
void SOUND_Open(sLONG_PTR *pResult, PackagePtr pParams);
void SOUND_Pause(sLONG_PTR *pResult, PackagePtr pParams);
void SOUND_Play(sLONG_PTR *pResult, PackagePtr pParams);
void SOUND_Stop(sLONG_PTR *pResult, PackagePtr pParams);
void SOUND_Close(sLONG_PTR *pResult, PackagePtr pParams);
void SOUND_Resume(sLONG_PTR *pResult, PackagePtr pParams);

#if VERSIONWIN
void sendCommand(wchar_t *commandString, C_TEXT &returnValue);
#endif	